// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkWaoJ_dR5AZhTKFiMCiQUhU0qyHI0ZcQ',
    appId: '1:1031627054377:web:5e3851dce19b7d9206ab38',
    messagingSenderId: '1031627054377',
    projectId: 'booking-dokter-online',
    authDomain: 'booking-dokter-online.firebaseapp.com',
    storageBucket: 'booking-dokter-online.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtLK4BOucU_bbzKbSeySgNXWUxKiig2so',
    appId: '1:1031627054377:android:20e02593a05a7afe06ab38',
    messagingSenderId: '1031627054377',
    projectId: 'booking-dokter-online',
    storageBucket: 'booking-dokter-online.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMWroH9f5mEKs4FmeKklh0vWSAIxw7Yxw',
    appId: '1:1031627054377:ios:98b4d0c42c855a6006ab38',
    messagingSenderId: '1031627054377',
    projectId: 'booking-dokter-online',
    storageBucket: 'booking-dokter-online.firebasestorage.app',
    iosBundleId: 'com.booking.dokter.aplikasiBookingDokter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMWroH9f5mEKs4FmeKklh0vWSAIxw7Yxw',
    appId: '1:1031627054377:ios:98b4d0c42c855a6006ab38',
    messagingSenderId: '1031627054377',
    projectId: 'booking-dokter-online',
    storageBucket: 'booking-dokter-online.firebasestorage.app',
    iosBundleId: 'com.booking.dokter.aplikasiBookingDokter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkWaoJ_dR5AZhTKFiMCiQUhU0qyHI0ZcQ',
    appId: '1:1031627054377:web:3ee824416e9359e106ab38',
    messagingSenderId: '1031627054377',
    projectId: 'booking-dokter-online',
    authDomain: 'booking-dokter-online.firebaseapp.com',
    storageBucket: 'booking-dokter-online.firebasestorage.app',
  );
}
